<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="MapTiles" tilewidth="16" tileheight="16" tilecount="64" columns="16">
 <image source="tilesets/map_tiles_tiled.png" width="256" height="64"/>
 <tile id="0" type="map"/>
 <tile id="1" type="map"/>
 <tile id="2" type="map"/>
 <tile id="3" type="map"/>
 <tile id="4" type="map"/>
 <tile id="5" type="map"/>
 <tile id="6" type="map"/>
 <tile id="7" type="map"/>
 <tile id="8" type="map"/>
 <tile id="9" type="map"/>
 <tile id="10" type="map"/>
 <tile id="11" type="map"/>
 <tile id="12" type="map"/>
 <tile id="13" type="map"/>
 <tile id="14" type="map"/>
 <tile id="15" type="map"/>
 <tile id="16" type="map"/>
 <tile id="17" type="map"/>
 <tile id="18" type="map"/>
 <tile id="19" type="map"/>
 <tile id="20" type="map"/>
 <tile id="21" type="map"/>
 <tile id="22" type="map"/>
 <tile id="23" type="map"/>
 <tile id="24" type="map"/>
 <tile id="25" type="map"/>
 <tile id="26" type="map"/>
 <tile id="27" type="map"/>
 <tile id="28" type="map"/>
 <tile id="29" type="map"/>
 <tile id="30" type="map"/>
 <tile id="31" type="map"/>
 <tile id="32" type="map"/>
 <tile id="33" type="map"/>
 <tile id="34" type="map"/>
 <tile id="35" type="map"/>
 <tile id="36" type="map"/>
 <tile id="37" type="map"/>
 <tile id="38" type="map"/>
 <tile id="39" type="map"/>
 <tile id="48" type="map"/>
 <tile id="49" type="map"/>
 <tile id="50" type="map"/>
 <tile id="51" type="map"/>
 <tile id="52" type="map"/>
 <tile id="53" type="map"/>
 <tile id="54" type="map"/>
 <tile id="55" type="map"/>
</tileset>
