FONT_BASE = 208
LETTERS_BASE = (FONT_BASE + 0)
NUMBERS_BASE = (FONT_BASE + 26)
SYMBOLS_BASE = (FONT_BASE + 36)

.charmap 65, (FONT_BASE + 0) ; A
.charmap 66, (FONT_BASE + 1) ; B
.charmap 67, (FONT_BASE + 2) ; C
.charmap 68, (FONT_BASE + 3) ; D
.charmap 69, (FONT_BASE + 4) ; E
.charmap 70, (FONT_BASE + 5) ; F
.charmap 71, (FONT_BASE + 6) ; G
.charmap 72, (FONT_BASE + 7) ; H
.charmap 73, (FONT_BASE + 8) ; I
.charmap 74, (FONT_BASE + 9) ; J
.charmap 75, (FONT_BASE + 10) ; K
.charmap 76, (FONT_BASE + 11) ; L
.charmap 77, (FONT_BASE + 12) ; M
.charmap 78, (FONT_BASE + 13) ; N
.charmap 79, (FONT_BASE + 14) ; O
.charmap 80, (FONT_BASE + 15) ; P
.charmap 81, (FONT_BASE + 16) ; Q
.charmap 82, (FONT_BASE + 17) ; R
.charmap 83, (FONT_BASE + 18) ; S
.charmap 84, (FONT_BASE + 19) ; T
.charmap 85, (FONT_BASE + 20) ; U
.charmap 86, (FONT_BASE + 21) ; V
.charmap 87, (FONT_BASE + 22) ; W
.charmap 88, (FONT_BASE + 23) ; X
.charmap 89, (FONT_BASE + 24) ; Y
.charmap 90, (FONT_BASE + 25) ; Z

.charmap 48, (FONT_BASE + 26) ; 0
.charmap 49, (FONT_BASE + 27) ; 1
.charmap 50, (FONT_BASE + 28) ; 2
.charmap 51, (FONT_BASE + 29) ; 3
.charmap 52, (FONT_BASE + 30) ; 4
.charmap 53, (FONT_BASE + 31) ; 5
.charmap 54, (FONT_BASE + 32) ; 6
.charmap 55, (FONT_BASE + 33) ; 7
.charmap 56, (FONT_BASE + 34) ; 8
.charmap 57, (FONT_BASE + 35) ; 9

.charmap 46, (FONT_BASE + 36) ; .
.charmap 44, (FONT_BASE + 37) ; ,
.charmap 33, (FONT_BASE + 38) ; !
.charmap 63, (FONT_BASE + 39) ; ?
.charmap 45, (FONT_BASE + 40) ; -
.charmap 36, (FONT_BASE + 41) ; $
.charmap 32, (FONT_BASE + 42) ; " "
;.charmap 46, (FONT_BASE + 43) ; 
;.charmap 46, (FONT_BASE + 44) ; 
;.charmap 46, (FONT_BASE + 45) ; 
;.charmap 46, (FONT_BASE + 46) ; 
.charmap 107, (FONT_BASE + 47) ; KEY, "k"



