.globalzp GameMode
.globalzp FadeToGameMode
.global CurrentBeatCounter
.global DisplayedRowCounter
.global AccumulatedGameBeats

.global run_kernel
.global init_engine
.global room_init
.global advance_to_next_floor
.global fade_to_game_mode
.global game_prep
.global title_prep
.global game_end_screen_prep

.globalzp PpuScrollX
.globalzp PpuScrollY
.globalzp PpuScrollNametable

.global ScreenShakeDepth
.global ScreenShakeSpeed
.global ScreenShakeDecayCounter