.global init_player
.global draw_player
.global determine_player_intent
.global update_player
.global damage_player

.global row_number_to_tile_index_lut

.global PlayerRow
.global PlayerCol
.global PlayerMaxHealth
.global PlayerHealth
.global PlayerWeapon
.global PlayerWeaponDmg
.globalzp PlayerWeaponPtr
.global PlayerRoomIndex
.global PlayerKeys
.global PlayerGold
.global PlayerSpriteIndex
.global PlayerZone
.global PlayerFloor
.global PlayerNextDirection

MAX_HEARTS = 7